
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
		#include "g_inc_uib.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "uib_app_manager.h"


/* event handler declarations */

uib_view_context* uib_view_view12_create(Evas_Object* parent, void* create_callback_param) {
	uib_view12_view_context* vc = calloc(1, sizeof(uib_view12_view_context));
	vc->parent = parent;
	vc->view_name = "view12";
	vc->indicator_state = ELM_WIN_INDICATOR_SHOW;
	vc->is_user_view = false;
	uib_app_manager_get_instance()->add_view_context((uib_view_context*)vc);
	if (!vc->grid11) {
		vc->grid11= elm_grid_add(parent);
		vc->root_container = vc->grid11;
	}
	uib_views_get_instance()->set_targeted_view((uib_view_context*)vc);

	//bind event handler


	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	uib_views_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_views_destroy_callback, vc);

	return (uib_view_context*)vc;
}
void uib_view12_config_CIRCLE_360x360_portrait() {
	uib_app_manager_st* uib_app_manager = uib_app_manager_get_instance();
	uib_view12_view_context* vc = (uib_view12_view_context*)uib_app_manager->find_view_context("view12");
	if(!vc) {
		return;
	}
	if(vc->grid11) {
		elm_grid_clear(vc->grid11, EINA_FALSE);
		evas_object_size_hint_align_set(vc->grid11, -1.0, -1.0);		evas_object_size_hint_weight_set(vc->grid11, 1.0, 1.0);		elm_grid_size_set(vc->grid11, 1000, 1000);
		if (!vc->bg11) {
			vc->bg11 = elm_bg_add(vc->grid11);
		}
		if(vc->bg11) {
			evas_object_size_hint_align_set(vc->bg11, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->bg11, 1.0, 1.0);			elm_bg_option_set(vc->bg11, (Elm_Bg_Option)ELM_BG_OPTION_SCALE);
			int hexValue = strtol("#ffffff"+1, NULL, 16);
			int r = (hexValue&0xFF0000)>>16;
			int g = (hexValue&0xFF00)>>8;
			int b = (hexValue&0xFF);
			elm_bg_color_set(vc->bg11, r, g, b);
			evas_object_show(vc->bg11);
		}
		if (!vc->button11) {
			vc->button11 = elm_button_add(vc->grid11);
		}
		if (vc->button11) {
			evas_object_size_hint_align_set(vc->button11, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->button11, 1.0, 1.0);			elm_object_text_set(vc->button11,_UIB_LOCALE("Pagos"));
			elm_object_style_set(vc->button11,"bottom");
			evas_object_show(vc->button11);
		}
		if (!vc->CiviPromo) {
			vc->CiviPromo = elm_button_add(vc->grid11);
		}
		if (vc->CiviPromo) {
			evas_object_size_hint_align_set(vc->CiviPromo, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->CiviPromo, 1.0, 1.0);			elm_object_text_set(vc->CiviPromo,_UIB_LOCALE("CiviPromo"));
			elm_object_style_set(vc->CiviPromo,"bottom");
			evas_object_show(vc->CiviPromo);
		}
		elm_grid_pack(vc->grid11, vc->bg11, 3, -3, 1047, 1011);		elm_grid_pack(vc->grid11, vc->button11, 303, 701, 356, 356);		elm_grid_pack(vc->grid11, vc->CiviPromo, 308, 31, 356, 356);		evas_object_show(vc->grid11);
	}
}

