
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
		#include "g_inc_uib.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "uib_app_manager.h"


/* event handler declarations */

uib_view_context* uib_view_Menu_Pagos_create(Evas_Object* parent, void* create_callback_param) {
	uib_Menu_Pagos_view_context* vc = calloc(1, sizeof(uib_Menu_Pagos_view_context));
	vc->parent = parent;
	vc->view_name = "Menu_Pagos";
	vc->indicator_state = ELM_WIN_INDICATOR_SHOW;
	vc->is_user_view = false;
	uib_app_manager_get_instance()->add_view_context((uib_view_context*)vc);
	if (!vc->grid7) {
		vc->grid7= elm_grid_add(parent);
		vc->root_container = vc->grid7;
	}
	uib_views_get_instance()->set_targeted_view((uib_view_context*)vc);

	//bind event handler


	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	uib_views_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_views_destroy_callback, vc);

	return (uib_view_context*)vc;
}
void uib_Menu_Pagos_config_CIRCLE_360x360_portrait() {
	uib_app_manager_st* uib_app_manager = uib_app_manager_get_instance();
	uib_Menu_Pagos_view_context* vc = (uib_Menu_Pagos_view_context*)uib_app_manager->find_view_context("Menu_Pagos");
	if(!vc) {
		return;
	}
	if(vc->grid7) {
		elm_grid_clear(vc->grid7, EINA_FALSE);
		evas_object_size_hint_align_set(vc->grid7, -1.0, -1.0);		evas_object_size_hint_weight_set(vc->grid7, 1.0, 1.0);		elm_grid_size_set(vc->grid7, 1000, 1000);
		if (!vc->bg7) {
			vc->bg7 = elm_bg_add(vc->grid7);
		}
		if(vc->bg7) {
			evas_object_size_hint_align_set(vc->bg7, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->bg7, 1.0, 1.0);			char *resource_path = NULL;
			uib_util_rm_get_resource_path(APP_RESOURCE_TYPE_IMAGE, "C:\\Users\\Usuario\\Pictures\\Fotos Civica", &resource_path);
			elm_bg_file_set(vc->bg7, resource_path, NULL);
			if(resource_path) {
				free(resource_path);
			}
			elm_bg_option_set(vc->bg7, (Elm_Bg_Option)ELM_BG_OPTION_SCALE);
			int hexValue = strtol("#33ff00"+1, NULL, 16);
			int r = (hexValue&0xFF0000)>>16;
			int g = (hexValue&0xFF00)>>8;
			int b = (hexValue&0xFF);
			elm_bg_color_set(vc->bg7, r, g, b);
			evas_object_show(vc->bg7);
		}
		if (!vc->button6) {
			vc->button6 = elm_button_add(vc->grid7);
		}
		if (vc->button6) {
			evas_object_size_hint_align_set(vc->button6, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->button6, 1.0, 1.0);			elm_object_text_set(vc->button6,_UIB_LOCALE("Transporte"));
			elm_object_style_set(vc->button6,"bottom");
			evas_object_show(vc->button6);
		}
		if (!vc->button7) {
			vc->button7 = elm_button_add(vc->grid7);
		}
		if (vc->button7) {
			evas_object_size_hint_align_set(vc->button7, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->button7, 1.0, 1.0);			elm_object_text_set(vc->button7,_UIB_LOCALE("Comercio"));
			elm_object_style_set(vc->button7,"bottom");
			evas_object_show(vc->button7);
		}
		elm_grid_pack(vc->grid7, vc->bg7, -5, 8, 997, 1006);		elm_grid_pack(vc->grid7, vc->button6, 538, -33, 356, 358);		elm_grid_pack(vc->grid7, vc->button7, 320, 727, 356, 358);		evas_object_show(vc->grid7);
	}
}

