
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

#ifndef UIB_VIEWS_INC_H_
#define UIB_VIEWS_INC_H_

#include "uib_Menu_Inicial_view.h"
#include "uib_Configuracion_PIN_view.h"
#include "uib_Menu_2_view.h"
#include "uib_Menu_Life_view.h"
#include "uib_view6_view.h"
#include "uib_Menu_Pagos_view.h"
#include "uib_Pago_Transporte_view.h"
#include "uib_Trans_Neg_view.h"
#include "uib_Trans_aprob_view.h"
#include "uib_view12_view.h"
#include "uib_view13_view.h"
#include "uib_view14_view.h"
#include "uib_Boton_Panico_view.h"
#include "uib_Rutas_view.h"
#include "uib_Report_view.h"

#endif /* UIB_VIEWS_INC_H_ */
